---
ReportDefinitions:
  - reportName: billCountReport
    summary: Bill Count Report
    version: 1.0.0
    moduleName: rainmaker-fin
    sourceColumns:
      - name: bill_date
        label: Bill Date
        type: epoch
        source: lba
        total: false
      - name: total_amount
        label: Total Amount
        type: number
        source: lba
        total: true
        rowTotal: true
      - name: bill_count
        label: Bill Count
        type: number
        source: lba
        total: true
        rowTotal: true
      - name: ulb
        label: ULB Name
        type: string
        source: lba
        total: false
        rowTotal: false
    searchParams:
      - name: schema_name
        label: Schema Name
        type: singlevaluelist
        pattern: 'list://jmc:Jammu Municipal Corporation,smc:Srinagar Municipal Corporation,jammu:Directorate of Urban Local Bodies Jammu,kashmir:Directorate of Urban Local Bodies Kashmir,akhnoor:Akhnoor Municipal Committee,ghomanhasan:Gho-Manhasan Municipal Committee,bishnah:Bishnah Municipal Committee,arnia:Arnia Municipal Committee,rspura:R.S. Pura Municipal Committee,khour:Khour Municipal Committee,jourian:Jourian Municipal Committee,samba:Samba Municipal Council,vijaypur:Vijaypur Municipal Committee,baribrahmana:Bari Brahmana Municipal Committee,ramgarh:Ramgarh Municipal Committee,hiranagar:Hiranagar Municipal Committee,kathua:Kathua Municipal Council,basholi:Basholi Municipal Committee,lakhanpur:Lakhanpur Municipal Committee,billawar:Billawar Municipal Committee,parole:Parole Municipal Committee,rajouri:Rajouri Municipal Council,sunderbani:Sunderbani Municipal Committee,kalakote:Kalakote Municipal Committee,nowshera:Nowshera Municipal Committee,thanamandi:Thanamandi Municipal Committee,kishtwar:Kishtwar Municipal Council,udhampur:Udhampur Municipal Council,chenani:Chenani Municipal Committee,ramnagar:Ramnagar Municipal Committee,reasi:Reasi Municipal Council,doda:Doda Municipal Council,thathri:Thathri Municipal Committee,bhaderwah:Bhaderwah Municipal Committee,ramban:Ramban Municipal Council,katra:Katra Municipal Committee,batote:Batote Municipal Committee,banihal:Banihal Municipal Committee,poonch:Poonch Municipal Council,surankote:Surankote Municipal Committee,anantnag:Anantnag Municipal Council,achabal:Achabal Municipal Committee,bijbehara:Bijbehara Municipal Committee,kokernag:Kokernag Municipal Committee,mattan:Mattan Municipal Committee,qazigund:Qazigund Municipal Committee,seerhamdan:Seer Hamdan Municipal Committee,dooruveerinag:Dooru-Veerinag Municipal Committee,pahalgam:Pahalgam Municipal Committee,kulgam:Kulgam Municipal Council,yaripora:Yaripora Municipal Committee,frisal:Frisal Municipal Committee,pulwama:Pulwama Municipal Council,pampore:Pampore Municipal Committee,tral:Tral Municipal Committee,khrew:Khrew Municipal Committee,awantipora:Awantipora Municipal Committee,shopian:Shopian Municipal Committee,ganderbal:Ganderbal Municipal Council,budgam:Budgam Municipal Council,khansahib:Khansahib Municipal Committee,beerwah:Beerwah Municipal Committee,chadoora:Chadoora Municipal Committee,chariesharief:Chare Sharief Municipal Committee,baramulla:Baramulla Municipal Council,sopore:Sopore Municipal Council,pattan:Pattan Municipal Committee,uri:Uri Municipal Committee,watergam:Watergam Municipal Committee,gulmargtangmarg:Gulmarg Tangmarg Municipal Committee,bandipora:Bandipora Municipal Council,sumbal:Sumbal Municipal Committee,hajin:Hajin Municipal Committee,kupwara:Kupwara Municipal Council,handwara:Handwara Municipal Committee,langate:Langate Municipal Committee,kunzer:Kunzer Municipal Committee,magam:Magam Municipal Committee,aishmuquam:Aishmuquam Municipal Committee,devsar:Devsar Municipal Committee'
        source: lba
        isMandatory: true
        searchClause: AND lba.schema_name = $schema_name
      - name: fromDate
        label: From Date
        type: epoch
        source: lba
        isMandatory: false
        searchClause: AND lba.bill_date >= TO_TIMESTAMP($fromDate / 1000)
      - name: toDate
        label: To Date
        type: epoch
        source: lba
        isMandatory: false
        searchClause: AND lba.bill_date <= TO_TIMESTAMP($toDate / 1000)
    query: >
      SELECT
        lba.bill_date,
        lba.total_amount,
        lba.bill_count,
        UPPER(lba.schema_name) as ulb
      FROM
        live_bills_all lba
      WHERE
        1=1
    orderby: ORDER By bill_date desc

  - reportName: collectionReport
    summary: Collection Report
    version: 1.0.0
    moduleName: rainmaker-fin
    sourceColumns:
      - name: created_date
        label: Created Date
        type: epoch
        source: ei
        total: false
      - name: tenant
        label: Tenant Id
        type: string
        source: ei
        total: false
      - name: transaction_count
        label: Transaction Count
        type: number
        source: ei
        total: true
        rowTotal: true
      - name: total_amount
        label: Total Amount
        type: number
        source: ei
        total: true
        rowTotal: true
    searchParams:
      - name: fromDate
        label: From Date
        type: epoch
        source: ei
        isMandatory: false
        searchClause: AND ei.createddate >= TO_TIMESTAMP($fromDate / 1000)
      - name: toDate
        label: To Date
        type: epoch
        source: ei
        isMandatory: false
        searchClause: AND ei.createddate <= TO_TIMESTAMP($toDate / 1000)
    query: >
          SELECT
          DATE(ei.createddate) AS created_date,
          UPPER(SPLIT_PART(ei.tenantid, '.', 2)) AS tenant,
          COUNT(*) AS transaction_count,
          SUM(ei.amount) AS total_amount
          FROM egf_instrument ei
          WHERE 1=1
    groupby: >
          GROUP BY
          DATE(ei.createddate),
          UPPER(SPLIT_PART(ei.tenantid, '.', 2))

    orderby: >
         ORDER BY
         created_date DESC,
         tenant